name: Practical-Exercise-QA

on: [push]

jobs:
  Prettier-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly

      - name: Run Prettier
        uses: actions/checkout@v2
        with:
           start: npm run check-format
